---
title: "Code Book"
author: "Christopher Campbell"
date: "October 25, 2015"
output: html_document
---

#Getting and Cleaning Data Coursera#

##A tidy data set created from the Human Activity Recognition Using Smartphones Data Set##
##Hosted by the Machine Learning Repository, http://archive.ics.uci.edu/ml/index.html.

###Code Book

The script, run_analysis.r, results in a tidy data set of 88 variables and 180 records (one record per 30 subjects and per 6 activities). 

Columns:
1. SubjectID - The subjects are identified in an integer vector from 1 to 30.
2. Activity - The activity being performed in a character vector consisting of the levels:
  "Walking"
  "Walking_upstairs"
  "Walking_downstairs"
  "Standing"
  "Sitting"
  "Laying"
3. Columns 3-88 contain the names of the measurements relating to mean and standard deviation.
  tBodyAcc-mean()-X 
  tBodyAcc-mean()-Y 
  tBodyAcc-mean()-Z 
  tGravityAcc-mean()-X 
  tGravityAcc-mean()-Y 
  tGravityAcc-mean()-Z 
  tBodyAccJerk-mean()-X 
  tBodyAccJerk-mean()-Y 
  tBodyAccJerk-mean()-Z 
  tBodyGyro-mean()-X 
  tBodyGyro-mean()-Y 
  tBodyGyro-mean()-Z 
  tBodyGyroJerk-mean()-X 
  tBodyGyroJerk-mean()-Y 
  tBodyGyroJerk-mean()-Z 
  tBodyAccMag-mean() 
  tGravityAccMag-mean() 
  tBodyAccJerkMag-mean() 
  tBodyGyroMag-mean() 
  tBodyGyroJerkMag-mean() 
  fBodyAcc-mean()-X 
  fBodyAcc-mean()-Y 
  fBodyAcc-mean()-Z 
  fBodyAcc-meanFreq()-X 
  fBodyAcc-meanFreq()-Y 
  fBodyAcc-meanFreq()-Z 
  fBodyAccJerk-mean()-X 
  fBodyAccJerk-mean()-Y 
  fBodyAccJerk-mean()-Z 
  fBodyAccJerk-meanFreq()-X 
  fBodyAccJerk-meanFreq()-Y 
  fBodyAccJerk-meanFreq()-Z 
  fBodyGyro-mean()-X 
  fBodyGyro-mean()-Y 
  fBodyGyro-mean()-Z 
  fBodyGyro-meanFreq()-X 
  fBodyGyro-meanFreq()-Y 
  fBodyGyro-meanFreq()-Z 
  fBodyAccMag-mean() 
  fBodyAccMag-meanFreq() 
  fBodyBodyAccJerkMag-mean() 
  fBodyBodyAccJerkMag-meanFreq() 
  fBodyBodyGyroMag-mean() 
  fBodyBodyGyroMag-meanFreq() 
  fBodyBodyGyroJerkMag-mean() 
  fBodyBodyGyroJerkMag-meanFreq() 
  angle(tBodyAccMean,gravity) 
  angle(tBodyAccJerkMean),gravityMean) 
  angle(tBodyGyroMean,gravityMean) 
  angle(tBodyGyroJerkMean,gravityMean) 
  angle(X,gravityMean) angle(Y,gravityMean) 
  angle(Z,gravityMean) 
  tBodyAcc-std()-X 
  tBodyAcc-std()-Y 
  tBodyAcc-std()-Z 
  tGravityAcc-std()-X 
  tGravityAcc-std()-Y 
  tGravityAcc-std()-Z 
  tBodyAccJerk-std()-X 
  tBodyAccJerk-std()-Y 
  tBodyAccJerk-std()-Z 
  tBodyGyro-std()-X 
  tBodyGyro-std()-Y 
  tBodyGyro-std()-Z 
  tBodyGyroJerk-std()-X 
  tBodyGyroJerk-std()-Y 
  tBodyGyroJerk-std()-Z 
  tBodyAccMag-std() 
  tGravityAccMag-std() 
  tBodyAccJerkMag-std() 
  tBodyGyroMag-std() 
  tBodyGyroJerkMag-std() 
  fBodyAcc-std()-X 
  fBodyAcc-std()-Y 
  fBodyAcc-std()-Z 
  fBodyAccJerk-std()-X 
  fBodyAccJerk-std()-Y 
  fBodyAccJerk-std()-Z 
  fBodyGyro-std()-X 
  fBodyGyro-std()-Y 
  fBodyGyro-std()-Z 
  fBodyAccMag-std() 
  fBodyBodyAccJerkMag-std() 
  fBodyBodyGyroMag-std() 
  fBodyBodyGyroJerkMag-std()

For more information about the measurement collection techniques, see
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

###Citations

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. A Public Domain Dataset for Human Activity Recognition Using Smartphones. 21th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning, ESANN 2013. Bruges, Belgium 24-26 April 2013.

Data.table package at:
https://github.com/Rdatatable/data.table

DPLYR package at:
https://github.com/hadley/dplyr